

services = {
    'voice_service': {'i': 'fa fa-comment w3-text-red', 'h3': 'Voice AI Services', 'p': 'Transform the way your virtual assistants, voice bots and audiobooks sound with our Voice AI Services. Our cutting-edge generative AI algorithms produce human-like speech that will make your audience engage with your brand like never before.', 'url':'https://ia.hadox.mx/ai_services/voice_services/lite/voice/GEN/'},
    'text_service': {'i': 'fa fa-file-text w3-text-blue', 'h3': 'Text AI Services', 'p': "Get custom, engaging and accurate text content for your brand's needs with our Text AI Services. Whether you need product descriptions, social media posts or news articles, our AI algorithms generate high-quality content that resonates with your audience.", 'url':'https://ia.hadox.mx/ai_services/text_services/lite/text/GEN/'},
    'sound_service': {'i': 'fa fa-music w3-text-orange', 'h3': 'Sound AI Services', 'p': "Elevate your audio branding and create unique soundscapes for your movies or video games with our Sound AI Services. Our generative AI algorithms produce customizable and one-of-a-kind audio experiences that will immerse your audience in your content.", 'url':'https://ia.hadox.mx/ai_services/sound_services/lite/sound/GEN/'},
    'bria_service': {'i': 'fa fa-music w3-text-orange', 'h3': 'Bria AI Services', 'p': "Elevate your audio branding and create unique soundscapes for your movies or video games with our Sound AI Services. Our generative AI algorithms produce customizable and one-of-a-kind audio experiences that will immerse your audience in your content.", 'url':'https://ia.hadox.mx/ai_services/bria_service/image/GEN/'},
    'video_service': {'i': 'fa fa-video-camera w3-text-teal', 'h3': 'Video AI Services', 'p': "Create stunning, engaging and informative video content for your brand with our Video AI Services. From corporate videos to social media content, our AI algorithms produce high-quality videos that capture your audience's attention and convey your message in a visually stunning way.", 'url':'https://ia.hadox.mx/ai_services/video_services/lite/video/GEN/'},
    'image_service': {'i': 'fa fa-camera w3-text-purple', 'h3': 'Image AI Services', 'p': "Unlock the potential of your brand's visual identity with our Image AI Services. Our generative AI algorithms create realistic, eye-catching and customized images that will enhance your product design or digital art projects.", 'url':'https://ia.hadox.mx/ai_services/image_services/lite/image/GEN/'},
    'twin_service': {'i': 'fa fa-clone w3-text-green', 'h3': 'Digital Twin Services', 'p': "Create a virtual replica of your physical assets and optimize their performance with our Digital Twin Services. Our advanced AI algorithms allow you to simulate, monitor and analyze the behavior of your assets in real-time, reducing downtime and increasing productivity.", 'url':'https://ia.hadox.mx/ai_services/digital_services/lite/digital/GEN/'},

}